import AppKit

/// Polls a pasteboard and forwards new text clips to a sink (the ClipStore).
/// Storage, dedupe, and capping live in ClipStore; this only detects changes and
/// filters out password/transient/empty copies. The pasteboard is injectable so
/// the filter logic is unit-testable without the user's real clipboard.
final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let onCapture: (String) -> Void
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Pasteboard markers we must never capture (passwords, transient, generated).
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.RestoredType"      // our own paste-backs (avoid a capture loop)
    ]

    init(pasteboard: NSPasteboard = .general, onCapture: @escaping (String) -> Void) {
        self.pasteboard = pasteboard
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.captureIfChanged()
        }
    }

    /// Detect a pasteboard change and forward the new text (if capturable).
    /// Returns true if a clip was forwarded. Internal for the timer + tests.
    @discardableResult
    func captureIfChanged() -> Bool {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return false }

        // Read representations, then re-check changeCount: if it advanced mid-read,
        // the pasteboard was rewritten under us — discard and let the next tick
        // re-capture a stable snapshot (leave lastChangeCount untouched so we retry).
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        let text = pasteboard.string(forType: .string)
        guard pasteboard.changeCount == changeCount else { return false }

        lastChangeCount = changeCount

        guard types.isDisjoint(with: ignoredTypes) else { return false }
        guard let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }

        onCapture(text)
        return true
    }
}
