import AppKit
import Combine

/// Minimal clipboard capture: polls a pasteboard and keeps recent text clips in
/// memory. Deliberately small — Phase 1 swaps the in-memory array for the Core
/// Data store and adds images/files, RestoredType handling, content-hash dedup,
/// and off-main extraction. The pasteboard is injectable so capture logic is
/// unit-testable without touching the user's real clipboard.
final class ClipboardMonitor: ObservableObject {
    static let shared = ClipboardMonitor()

    @Published private(set) var clips: [String] = []

    private let pasteboard: NSPasteboard
    private let maxItems: Int
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Pasteboard markers we must never capture (passwords, transient, generated).
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init(pasteboard: NSPasteboard = .general, maxItems: Int = 50) {
        self.pasteboard = pasteboard
        self.maxItems = maxItems
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        // Start fresh: only capture new copies from launch onward.
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.captureIfChanged()
        }
    }

    /// Capture the pasteboard if it changed since last seen. Returns true if a new
    /// clip was stored. Exposed (internal) for the timer and unit tests.
    @discardableResult
    func captureIfChanged() -> Bool {
        guard pasteboard.changeCount != lastChangeCount else { return false }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: ignoredTypes) else { return false }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }

        if clips.first == text { return false }     // ignore immediate repeats
        clips.removeAll { $0 == text }               // de-dupe: move existing to top
        clips.insert(text, at: 0)
        if clips.count > maxItems { clips.removeLast(clips.count - maxItems) }
        return true
    }
}
