import AppKit

/// Polls a pasteboard and forwards new text clips to a sink (the ClipStore).
/// Storage, dedupe, and capping live in ClipStore; this only detects changes and
/// filters out password/transient/empty copies. The pasteboard is injectable so
/// the filter logic is unit-testable without the user's real clipboard.
@MainActor
final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let shouldCapture: () -> Bool
    private let onCapture: (String) -> Void
    private let onCaptureImage: (Data) -> Void
    private let isExcluded: (String?) -> Bool
    private var timer: Timer?
    private var activationObserver: NSObjectProtocol?
    private var lastChangeCount: Int
    /// Whether the app that's currently frontmost is one we never record from. Tracked from
    /// activation events so a copy made *inside* an excluded app can be discarded the moment
    /// focus leaves it — before the 0.5s poll tick (which samples the new, allowed frontmost app)
    /// could capture it.
    private var currentAppExcluded = false

    /// Pasteboard markers we must never capture (passwords, transient, generated).
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.RestoredType"      // our own paste-backs (avoid a capture loop)
    ]

    init(pasteboard: NSPasteboard = .general,
         shouldCapture: @escaping () -> Bool = { true },
         onCapture: @escaping (String) -> Void,
         onCaptureImage: @escaping (Data) -> Void = { _ in },
         isExcluded: @escaping (String?) -> Bool = { _ in false }) {
        self.pasteboard = pasteboard
        self.shouldCapture = shouldCapture
        self.onCapture = onCapture
        self.onCaptureImage = onCaptureImage
        self.isExcluded = isExcluded
        self.lastChangeCount = pasteboard.changeCount
    }

    deinit {
        if let activationObserver { NSWorkspace.shared.notificationCenter.removeObserver(activationObserver) }
    }

    /// Discard anything an excluded app put on the pasteboard once focus leaves it, so a copy
    /// made inside (e.g.) a password manager isn't captured after switching to a normal app.
    /// Internal for tests. `newBundleID` is the app that just became frontmost.
    func handleFrontmostChange(newBundleID: String?) {
        let nowExcluded = isExcluded(newBundleID)
        if currentAppExcluded && !nowExcluded {
            lastChangeCount = pasteboard.changeCount   // skip whatever the excluded app copied
        }
        currentAppExcluded = nowExcluded
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        currentAppExcluded = isExcluded(NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
        ) { [weak self] note in
            MainActor.assumeIsolated {
                let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication
                self?.handleFrontmostChange(newBundleID: app?.bundleIdentifier)
            }
        }
        // Run in .common modes so polling keeps firing during tracking loops
        // (menu open, dragging the palette) instead of stalling in .default.
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            // The timer is added to RunLoop.main, so it always fires on the main thread.
            MainActor.assumeIsolated { _ = self?.captureIfChanged() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Detect a pasteboard change and forward the new text (if capturable).
    /// Returns true if a clip was forwarded. Internal for the timer + tests.
    @discardableResult
    func captureIfChanged() -> Bool {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return false }

        // Fail closed while an excluded app is (or was just) the current one. The activation
        // notification that advances lastChangeCount is delivered async, so a tick can land after
        // focus left the excluded app but before that handler runs — `currentAppExcluded` is the
        // lagging signal that still reflects the excluded app, so we skip (and consume the change)
        // rather than capture its copy into a now-allowed frontmost.
        guard !currentAppExcluded else { lastChangeCount = changeCount; return false }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        // Skip ignored markers (concealed/transient/auto-generated/our-own-paste) BEFORE reading
        // the value — never materialize a password-manager string into memory.
        guard types.isDisjoint(with: ignoredTypes) else { lastChangeCount = changeCount; return false }

        // Read the cheap text representation, then re-check changeCount: if it advanced mid-read,
        // the pasteboard was rewritten under us — discard and let the next tick re-capture.
        let text = pasteboard.string(forType: .string)
        guard pasteboard.changeCount == changeCount else { return false }

        lastChangeCount = changeCount

        // Capture gate (pause / excluded-app / password-manager) before materializing image bytes.
        guard shouldCapture() else { return false }

        let trimmed = text?.trimmingCharacters(in: .whitespacesAndNewlines)
        let hasImage = types.contains(NSPasteboard.PasteboardType.png.rawValue)
            || types.contains(NSPasteboard.PasteboardType.tiff.rawValue)

        // Prefer text — unless it's just a single-line URL accompanying an image (e.g. "copy
        // image" in a browser), where the image is what the user wants.
        if let trimmed, !trimmed.isEmpty, !(hasImage && !trimmed.contains("\n") && ClipKind.detect(from: trimmed) == .link) {
            onCapture(text!)
            return true
        }
        guard hasImage, let image = imageBytes() else { return false }
        guard pasteboard.changeCount == changeCount else { return false }   // torn-read guard for the image read
        onCaptureImage(image)
        return true
    }

    private static let maxImageBytes = 32 * 1024 * 1024   // skip absurdly large images (would block the poll)

    /// Image bytes for the blob: prefer PNG; convert TIFF → PNG; if conversion fails, keep the
    /// raw TIFF (don't silently drop). nil if absent or over the size cap.
    private func imageBytes() -> Data? {
        if let png = pasteboard.data(forType: .png) {
            return png.count <= Self.maxImageBytes ? png : nil
        }
        guard let tiff = pasteboard.data(forType: .tiff), tiff.count <= Self.maxImageBytes else { return nil }
        if let rep = NSBitmapImageRep(data: tiff), let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return tiff   // unconvertible TIFF → store as-is (paste-back sniffs the type)
    }
}
